all:
  vars:
    ansible_user: debian
    ansible_python_interpreter: /usr/bin/python3
    k3s_flannel_iface: enp2s0f1
    k3s_data_dir: /home/k3s-data
    k3s_storage_dir: /home/k3s-storage

  children:
    k3s_server:
      hosts:
        k8s-node01:
          ansible_host: 192.168.0.200
          cluster_ip: 10.10.10.11

    k3s_workers:
      hosts:
        k8s-node02:
          ansible_host: 192.168.0.201
          cluster_ip: 10.10.10.12
